### ISSUE TITLE
5.4.6 build is still failing. 

### ISSUE THREAD

**Issue by tobzsc** [OpenNebula/packages#10]
Please see #9 and the last lines. There seems to be something wrong and it does not have to anything with the manpages.

**Comment by vholer** [comment]
Sorry, I haven't noticed that. I can see...

For building ONE 5.4.x you need to take a packages' branch one-5.4 (https://github.com/OpenNebula/packages/tree/one-5.4). In the packages' master there are changes for the ONE development version already. So, basically please align the branches of the repositories you are using.

Sorry for any inconveniences.

Best regards,
Vlastimil Holer
