### ISSUE TITLE
CentOS 8 install_gems dependency issue.

### ISSUE THREAD

**Issue by jamesarems** [OpenNebula/packages#115]
CentOS 8 install_gems dependency issue.

Issue:

    Error:
    Problem: problem with installed package zeromq3-devel-3.2.5-3.el8.x86_64

        package zeromq3-devel-3.2.5-3.el8.x86_64 conflicts with zeromq-devel(x86-64) provided by zeromq-devel-2.2.0-4.el8.x86_64

CentOS/ RHEL 8 is using zeromq3 , zeromq3-devel by default.

**Comment by vholer** [comment]
Since `zeromq` (4.x) is finally in EPEL, `install_gems` should work as is.
I have added only extra redhat-rpm-config package necessary for hardened GCC builds.
