### ISSUE TITLE
OpenNebula 5.4.9 build issues

### ISSUE THREAD

**Issue by hydro-b** [OpenNebula/packages#18]
Hi,

I followed the "build guide" to build one-5.4.9 packages. I have done so succesfully in the past (one-5.4.3 with externally copied man pages) but now I seem to hit several issues. During the build of "man pages" there are a bunch of functions that give a ruby dependency error. See attached file "build_man_pages.txt". The man pages do seem to be built correctly, so it might be a unit test that might be failing.

The CentOS 7 build fails with the following message:

+ install -p -D -m 644 share/pkgs/logrotate/opennebula-econe /root/rpmbuild/BUILDROOT/opennebula-5.4.9-1.x86_64/etc/logrotate.d/opennebula-econe
install: cannot stat 'share/pkgs/logrotate/opennebula-econe': No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.7C69GM (%install)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.7C69GM (%install)
{code}

The debian / ubuntu build reports a lot of "opennebula source: source-is-missing" regardig "bower_components". See for build info one-5.4.9.buildoutput.txt and opennebula_5.4.9-1_amd64.build.txt

Attachments:

[build_man_pages.txt](https://github.com/OpenNebula/packages/files/1814572/build_man_pages.txt)

[one-5.4.9.buildoutput.txt](https://github.com/OpenNebula/packages/files/1814634/one-5.4.9.buildoutput.txt)
[opennebula_5.4.9-1_amd64.build.txt](https://github.com/OpenNebula/packages/files/1814638/opennebula_5.4.9-1_amd64.build.txt)

**Comment by vholer** [comment]
Hello,

> See attached file "build_man_pages.txt". The man pages do seem to be built correctly, so it might be a unit test that might be failing.

manual pages are built from the help provided by each tool (as a transformed output of particular tool executed with --help), if the tool depends on any external library (usually installed by install_gems script) and this library is missing, you get an error. For now I don't have anything better than to install missing gems before generating the manual pages.

> install: cannot stat 'share/pkgs/logrotate/opennebula-econe': No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.7C69GM (%install)
> RPM build errors:
> Bad exit status from /var/tmp/rpm-tmp.7C69GM (%install)

For buildling ONE 5.4.x you need to take a `one-5.4` branch of the packages. Master is aligned with the ONE master.

Best regards,
Vlastimil

**Comment by hydro-b** [comment]
On Wed, Mar 21, 2018 at 01:44:01PM +0000, Vlastimil Holer wrote:
> Hello,
> 
> > See attached file "build_man_pages.txt". The man pages do seem to be
> > built correctly, so it might be a unit test that might be failing.
> 
> manual pages are built from the help provided by each tool (as a
> transformed output of particular tool executed with --help), if the
> tool depends on any external library (usually installed by
> install_gems script) and this library is missing, you get an error.
> For now I don't have anything better than to install missing gems
> before generating the manual pages.

Yup, so I did that. No the cleanest solution, but proably good enough.
Feels a bit weird / backward to install ONE 5.4.6 and use that to generate man
pages for ONE 5.4.9 ... But they get build fine.

> 
> > install: cannot stat 'share/pkgs/logrotate/opennebula-econe': No
> > such file or directory
> error: Bad exit status from /var/tmp/rpm-tmp.7C69GM (%install)
> > RPM build errors: Bad exit status from /var/tmp/rpm-tmp.7C69GM
> > (%install)
> 
> For buildling ONE 5.4.x you need to take a `one-5.4` branch of the
> packages. Master is aligned with the ONE master.

Sure, I did that. I recreated the 5.4.9.tar.gz and rebuild for ubuntu,
still breaks:

dh_install: opennebula missing files: dist/usr/lib/one/ruby/opennebula_driver.rb
dh_install: missing files, aborting
debian/rules:37: recipe for target 'override_dh_auto_install' failed
make[1]: *** [override_dh_auto_install] Error 2
make[1]: Leaving directory '/build/opennebula-5.4.9'
debian/rules:23: recipe for target 'binary' failed
make: *** [binary] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
I: copying local configuration
E: Failed autobuilding of package
I: unmounting dev/pts filesystem
I: unmounting run/shm filesystem
I: unmounting proc filesystem
I: cleaning the build env 
I: removing directory /var/cache/pbuilder/build/12641 and its subdirectories

^^ any idea why this breaks, dist/usr/lib/one/ruby/opennebula_driver.rb is
missing?

Thanks,

Stefan

**Comment by vholer** [comment]
Hello Stefan,

> Yup, so I did that. No the cleanest solution, but proably good enough.
Feels a bit weird / backward to install ONE 5.4.6 and use that to generate man
pages for ONE 5.4.9 ... But they get build fine.

I thought that just (manually) installing those 2 gems (AWS, sequal) would be enough. Not all the ONE dependencies. But, I didn't try it. You are absolutely right this is not ideal....

> Sure, I did that. I recreated the 5.4.9.tar.gz and rebuild for ubuntu, still breaks:

I'm afraid you aren't doing that. You need to align branches from **both repositories**. Take:
- https://github.com/OpenNebula/one/tree/one-5.4
- https://github.com/OpenNebula/packages/tree/one-5.4

For the particular version, let's say the 5.4.9, take the state represented by tags:
- https://github.com/OpenNebula/one/tree/release-5.4.9
- https://github.com/OpenNebula/packages/tree/release-5.4.9

If you end up combining one-5.4 branch for ONE, and master branch for packages, it'll fail on the error you are experiencing. The `opennebula_driver.rb` is the new thing in the ONE master, and packages master is also modified to be able to create packages for ONE master with this new driver.

Best,
Vlastimil

**Comment by hydro-b** [comment]
On Fri, Mar 23, 2018 at 06:56:09AM -0700, Vlastimil Holer wrote:
> Hello Stefan,
> 
> > Yup, so I did that. No the cleanest solution, but proably good enough.
> Feels a bit weird / backward to install ONE 5.4.6 and use that to generate man
> pages for ONE 5.4.9 ... But they get build fine.
> 
> I thought that just (manually) installing those 2 gems (AWS, sequal) would be enough. Not all the ONE dependencies. But, I didn't try it. You are absolutely right this is not ideal....
> 
> > Sure, I did that. I recreated the 5.4.9.tar.gz and rebuild for ubuntu, still breaks:
> 
> I'm afraid you aren't doing that. You need to align branches from **both repositories**. Take:
> - https://github.com/OpenNebula/one/tree/one-5.4
> - https://github.com/OpenNebula/packages/tree/one-5.4
> 
> For the particular version, let's say the 5.4.9, take the state represented by tags:
> - https://github.com/OpenNebula/one/tree/release-5.4.9
> - https://github.com/OpenNebula/packages/tree/release-5.4.9
> 
> If you end up combining one-5.4 branch for ONE, and master branch for
> packages, it'll fail on the error you are experiencing. The
> `opennebula_driver.rb` is the new thing in the ONE master, and
> packages master is also modified to be able to create packages for ONE
> master with this new driver.

[root@one-builder opennebula-5.4.9]# git status
# HEAD detached at release-5.4.9
nothing to commit, working directory clean
[root@one-builder opennebula-5.4.9]# cd ..
[root@one-builder ~]# cd packages/
[root@one-builder packages]# git status
# On branch master
nothing to commit, working directory clean

^^ I completely missed the packages checkout. Thanks for pointing it out
to me. Builds fine now.

\o/

Gr. Stefan

**Comment by vholer** [comment]
Perfect, thank you. So I'm going to close this issues for now.
