### ISSUE TITLE
Building One 5.4.3 release fails

### ISSUE THREAD

**Issue by tkald** [OpenNebula/packages#2]
Having trouble building OpenNebula version 5.4.3. No problem with 5.4.2 version.

Build fails with error:

> dh_installman
>         install -d debian/opennebula/usr/share/man/man1/
>         install -p -m0644 debian/manpages/econe-server.1 debian/opennebula/usr/share/man/man1/econe-server.1
>         install -p -m0644 debian/manpages/mm_sched.1 debian/opennebula/usr/share/man/man1/mm_sched.1
>         install -p -m0644 debian/manpages/one.1 debian/opennebula/usr/share/man/man1/one.1
>         install -p -m0644 debian/manpages/oned.1 debian/opennebula/usr/share/man/man1/oned.1
> share/man/onedb.1: No such file or directory at /usr/bin/dh_installman line 131.
> debian/rules:23: recipe for target 'binary' failed
> make: *** [binary] Error 2
> dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
> I: copying local configuration
> E: Failed autobuilding of package
> I: unmounting dev/pts filesystem
> I: unmounting run/shm filesystem
> I: unmounting proc filesystem
> I: cleaning the build env
> I: removing directory /var/cache/pbuilder/build/17931 and its subdirectories
> 

Building Ubuntu 16.04 packages for Ubuntu 16.04

**Comment by vholer** [comment]
Hello, sorry for the problems with building

**Comment by vholer** [comment]
Hello,

sorry for problems with the packaging. The manual pages for few last releases were pre-generated by a script, which wasn't public. Now, when 5.4.6 is released, we have fixed both master + one-5.4 (for any **future** release) branches and placed a working script inside `share/man/build.sh` (use from here if missing in your particular checkout https://github.com/OpenNebula/one/blob/152189215e2c67406181cb30fe6397a413842562/share/man/build.sh).

The manual pages need to be generated when creating a release archive, please check https://github.com/OpenNebula/packages/#create-archive.

Thank you and sorry for the problems,
Vlastimil Holer

Also reported in:
https://github.com/OpenNebula/packages/issues/9
https://github.com/OpenNebula/packages/issues/6
https://github.com/OpenNebula/packages/issues/2
