### ISSUE TITLE
Can't install opennebula-node in chroot

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/packages#29]
Hi since version `5.6` opennebula-node can't be installed in chroot.
The main reason this line in `opennebula-node.postinst` script:
```
systemctl try-restart libvirt-bin
```
It is required running systemd but inside chroot it will return an error:
```
Failed to connect to bus: No such file or directory
dpkg: error processing package opennebula-node (--configure):
 subprocess installed post-installation script returned error exit status 1
```
The useful workaround which is usually used for debian packages:
```
systemctl try-restart libvirtd 2> /dev/null || true
```

**Comment by vholer** [comment]
Merged, thank you!
