### ISSUE TITLE
Automatic systemd reload

### ISSUE THREAD

**Issue by vholer** [OpenNebula/packages#33]
On package install / upgrade, there should be an automatic systemd reload so that user isn't forcecd to do it manually. Avoid following situation:

```
# systemctl start opennebula
Warning: opennebula.service changed on disk. Run 'systemctl daemon-reload' to reload units.
```

**Comment by vholer** [comment]
Reopening, doesn't reload systemd on C7 reinstall:

```
# yum reinstall $(rpm -qa | grep -i opennebula)
# systemctl start opennebula
Warning: opennebula.service changed on disk. Run 'systemctl daemon-reload' to reload units.
```

**Comment by xorel** [comment]
Can't reproduce the reinstall but missing reload on upgrade should fix https://github.com/OpenNebula/packages/pull/60 (+ fix the %postun section)
