### ISSUE TITLE
Build procedure of sunstone in README.md not working since 5.5.90

### ISSUE THREAD

**Issue by mingjin** [OpenNebula/packages#35]
Please refer to the [thread](https://forum.opennebula.org/t/sunstone-not-loading-on-5-6-beta1/6140/3) on Opennebula forum.

### Symptom
If user follow the build procedure of sunstone in README.md, the building and installation process would be successful. User can also access Sunstone's login page, but when user log in, the dashboard endlessly loads. Can’t use sunstone.

### Analysis
The build script of sunstone has changed since version 5.5.90. It used to be
```
# sunstone
cd src/sunstone/public
npm install -g bower grunt grunt-cli
npm install
bower install --allow-root --config.interactive=false
grunt sass
grunt requirejs
rm -rf node_modules/
cd ../../../../
```
In fact, it should be
```
# sunstone
cd  src/sunstone/public
./build.sh -d
export PATH=$PATH:$PWD/node_modules/.bin
./build.sh
rm -rf node_modules/
cd ../../../../
```
After that, everything works fine.

### Solution
Update the build script of sunstone in README.md to 
```
# sunstone
cd  src/sunstone/public
./build.sh -d
export PATH=$PATH:$PWD/node_modules/.bin
./build.sh
rm -rf node_modules/
cd ../../../../
```

**Comment by vholer** [comment]
Merged PR #63 

Thanks for the contribution.
