### ISSUE TITLE
Build relese 5.4.5 failed

### ISSUE THREAD

**Issue by UAnton** [OpenNebula/packages#6]
root@ubuntu:~/release-5.4.5/packages# ./ubuntu1710.sh https://github.com/OpenNebula/one/archive/release-5.4.5.tar.gz
./ubuntu1710.sh: line 47: cd: release-5.4.5: No such file or directory

Directory name is - one-release-5.4.5

**Comment by vholer** [comment]
Hello,

sorry for problems with the packaging. The manual pages for few last releases were pre-generated by a script, which wasn't public. Now, when 5.4.6 is released, we have fixed both master + one-5.4 (for any **future** release) branches and placed a working script inside `share/man/build.sh` (use from here if missing in your particular checkout https://github.com/OpenNebula/one/blob/152189215e2c67406181cb30fe6397a413842562/share/man/build.sh).

The manual pages need to be generated when creating a release archive, please check https://github.com/OpenNebula/packages/#create-archive.

Thank you and sorry for the problems,
Vlastimil Holer

Also reported in:
https://github.com/OpenNebula/packages/issues/9
https://github.com/OpenNebula/packages/issues/6
https://github.com/OpenNebula/packages/issues/2
