### ISSUE TITLE
Unable to build 5.8.0

### ISSUE THREAD

**Issue by hydro-b** [OpenNebula/packages#62]
I'm trying to build ONE 5.8.0 for 16.04 and 18.04 on Ubuntu Xenial but I'm running into "unknown dpkg-buildpackage/debuild option:"

/packages# ./ubuntu1804.sh https://downloads.opennebula.org/packages/opennebula-5.8.0/opennebula-5.8.0.tar.gz
--2019-02-26 21:24:33--  http://downloads.opennebula.org/extra/xmlrpc-c.tar.gz
Resolving downloads.opennebula.org (downloads.opennebula.org)... 173.255.246.101
Connecting to downloads.opennebula.org (downloads.opennebula.org)|173.255.246.101|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 818490 (799K) [application/x-gzip]
Saving to: âxmlrpc-c.tar.gzâ

xmlrpc-c.tar.gz                                             100%[========================================================================================================================================>] 799.31K  1.04MB/s    in 0.8s    

2019-02-26 21:24:34 (1.04 MB/s) - âxmlrpc-c.tar.gzâ saved [818490/818490]

build_opennebula.sh
xml_parse_huge.patch
debuild: unknown dpkg-buildpackage/debuild option: --source-option=--include-binaries
 dpkg-buildpackage -rfakeroot -d -us -uc -S --source-option=--include-binaries
dpkg-buildpackage: warning: using a gain-root-command while being root
dpkg-buildpackage: source package opennebula
dpkg-buildpackage: source version 5.8.0-1
dpkg-buildpackage: source distribution unstable
dpkg-buildpackage: source changed by OpenNebula Team <contact@opennebula.org>
 dpkg-source --include-binaries --before-build opennebula-5.8.0
dpkg-source: info: using options from opennebula-5.8.0/debian/source/local-options: --unapply-patches --abort-on-upstream-changes
dpkg-source: info: applying emulator.diff
 fakeroot debian/rules clean
dh clean --with javahelper,bash-completion,systemd
dh: unable to load addon systemd: Can't locate Debian/Debhelper/Sequence/systemd.pm in @INC (you may need to install the Debian::Debhelper::Sequence::systemd module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at (eval 17) line 2.
BEGIN failed--compilation aborted at (eval 17) line 2.

debian/rules:23: recipe for target 'clean' failed
make: *** [clean] Error 2
dpkg-buildpackage: error: fakeroot debian/rules clean gave error exit status 2
debuild: fatal error at line 1376:
dpkg-buildpackage -rfakeroot -d -us -uc -S --source-option=--include-binaries failed

Does ONE 5.8.0 needs to be build on a newer version of Ubuntu?

**Comment by vholer** [comment]
Please install `dh-systemd` package, it's missing in the build documentation right now.
