### ISSUE TITLE
LXD package polishments

### ISSUE THREAD

**Issue by vholer** [OpenNebula/packages#70]
Just small changes to improve the 5.8+ package:

opennebula-node-lxd.postrm
- fix formatting
- run only for remove + purge (modules config) actions
- silently fail if oneadmin is not in lxd group anymore!

opennebula-node-lxd.postinst
- fix formatting
- check if oneadmin is not in group lxd already
- if modules configs exists, we shouldn't just silly append into them!
- probably useless sudo entry on ubuntu1810
```
echo "oneadmin ALL=(ALL:ALL) NOPASSWD: /usr/bin/lxc" >> /etc/sudoers.d/opennebula-lxd
```

**Comment by dann1** [comment]
>probably useless sudo entry on ubuntu1810
> echo "oneadmin ALL=(ALL:ALL) NOPASSWD: /usr/bin/lxc" >> /etc/sudoers.d/opennebula-lxd

This is required for the code to work, it's the host setting required for the hacks for snapd, on the code to work.

**Comment by vholer** [comment]
@dann1 Which code depends on configured sudo against non-existing command?

```
root@ubuntu1810-lxd-ssh-85bad-1:~# file /usr/bin/lxc
/usr/bin/lxc: cannot open `/usr/bin/lxc' (No such file or directory)
```

If this really solves something, I would like to see a comment around this sudo reconfiguration + reference to a ONE issue for tracking purposes. Otherwise, it's something anybody would drop immediately.

**Comment by dann1** [comment]
tests were failing, it was wrong, I guess somehow the transitional lxd package from apt in ubuntu 1810 linked `/snap/bin/lxc` to `/usr/bin/lxc`. The code that relies on that is, the creation of the vnc connection to svncterm and some part of the network driver, when getting the tap interface, during post

**Comment by dann1** [comment]
> If this really solves something, I would like to see a comment around this sudo reconfiguration + reference to a ONE issue for tracking purposes. Otherwise, it's something anybody would drop immediately.

I think you [opened an issue](https://github.com/OpenNebula/one/issues/3046) for that already

**Comment by vholer** [comment]
> tests were failing, it was wrong, I guess somehow the transitional lxd package from apt in ubuntu 1810 linked `/snap/bin/lxc` to `/usr/bin/lxc`. The code that relies on that is, the creation of the vnc connection to svncterm and some part of the network driver, when getting the tap interface, during post
> 
> [This PR](https://github.com/OpenNebula/packages/pull/72) should fix the entry

So, until my complain we didn't notice this path is wrong and that something doesn't work? After the sudo fix, some tests should start passing. Which tests?

> I think you opened an issue for that already

That's different thing.

**Comment by dann1** [comment]
Prior to the lxd package update, tests installed 1810 via the apt transitional package, which i guess made the symlinks possible.

1. Tests were cool
2. Tests failed, lxd 3.12 came out
3. LXD package was updated
4. Tests complained about no lxc command because running them via ssh, don't include /snap/bin in PATH

The tests that failed were the ones that use lxc commands, like lxd-90 and lxd-91

In the issue you mention to get rid of the snap hack, the hack is sudoing lxc cli on oneadmin, and it's mostly code, but also the sudo entry for setting up the node

**Comment by vholer** [comment]
Thanks for the detailed explanation! I have the (sudo lxd) PR in my TODO.

**Comment by vholer** [comment]
Fixed by https://github.com/OpenNebula/packages/pull/77
