### ISSUE TITLE
Support pve-qemu packages

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/packages#85]
Proxmox have always well tested latest kernels and qemu versions in community repo, which is working fine on any ubuntu/debian distro, not only with proxmox.
I glad to use pve-qemu and pve-kernel in our environment and do not understand why opennebula packages should conflict with them.

**Comment by vholer** [comment]
That sounds very interesting, thanks for the proposal and PR!!

We have to check these Proxmox packages first and we can consider that for 5.10.

**Comment by kvaps** [comment]
From myself I can add that we're using pve-qemu and pve-kernel packages on ubuntu for compute nodes already more then one year, it was working fine on ubuntu16.04 and now is working fine on ubuntu18.04, proxmox itself using debian9 (and now debian10) as base for proxmox distro

**Comment by vholer** [comment]
@kvaps Pardon me, but how these packages can work fine on your Ubuntu 18.04, when the dependencies on Ubuntu aren't met? E.g., trying this repository:

```
deb http://download.proxmox.com/debian/pve XXXXX pve-no-subscription
```

When having XXXXXX suite with following unmet dependencies:

* **jessie**:

```
 pve-qemu-kvm : Depends: libjpeg62-turbo (>= 1.3.1) but it is not installable
                Depends: pve-libspice-server1 (>= 0.12.5-1) but it is not going to be installed
                Depends: libgnutls-deb0-28 (>= 3.3.0) but it is not installable
                Depends: libnettle4 (>= 2.6) but it is not installable
                Depends: libpng12-0 (>= 1.2.13-4) but it is not installable
```

* **stretch**:

```
 pve-qemu-kvm : Depends: libjpeg62-turbo (>= 1.3.1) but it is not installable
                Depends: pve-libspice-server1 (>= 0.12.5-1) but it is not going to be installed
```

* **buster** (OK, buster is too new):

```
 pve-qemu-kvm : Depends: libgfapi0 but it is not installable or
                         glusterfs-common (>= 5.6) but it is not going to be installed
                Depends: libgfchangelog0 but it is not installable or
                         glusterfs-common (>= 5.6) but it is not going to be installed
                Depends: libgfdb0 but it is not installable or
                         glusterfs-common (>= 5.6) but it is not going to be installed
                Depends: libgfrpc0 but it is not installable or
                         glusterfs-common (>= 5.6) but it is not going to be installed
                Depends: libgfxdr0 but it is not installable or
                         glusterfs-common (>= 5.6) but it is not going to be installed
                Depends: libglusterfs-dev but it is not installable or
                         glusterfs-common (>= 5.6) but it is not going to be installed
                Depends: libglusterfs0 but it is not installable or
                         glusterfs-common (>= 5.6) but it is not going to be installed
                Depends: libiscsi7 (>= 1.18.0) but 1.17.0-1.1 is to be installed
                Depends: libjemalloc2 (>= 5.0.0) but it is not installable
                Depends: libjpeg62-turbo (>= 1.3.1) but it is not installable
                Depends: libusb-1.0-0 (>= 2:1.0.22) but 2:1.0.21-2 is to be installed
                Depends: libc6 (>= 2.28) but 2.27-3ubuntu1 is to be installed
                Depends: l pve-qemu-kvm : Depends: libjpeg62-turbo (>= 1.3.1) but it is not installable
                Depends: pve-libspice-server1 (>= 0.12.5-1) but it is not going to be installed
ibglib2.0-0 (>= 2.57.2) but 2.56.3-0ubuntu0.18.04.1 is to be installed
                Depends: libgnutls30 (>= 3.6.6) but 3.5.18-1ubuntu1 is to be installed
```

The closest matching Debian to Ubuntu 18.04 is stretch, but do I understand right that you build `libjpeg62-turbo` for Ubuntu on your own or use some PPA to meet the dependencies?

I don't have anything against `pve-qemu-kvm` alternative on Debians. But on Ubuntus, it's not that straightforward and doesn't look good to me to enable it in the packages.

**Comment by kvaps** [comment]
Hi, I've just checked my builds, yes, I use `libjpeg62-turbo` from debian's repo:
http://ftp.cz.debian.org/debian/pool/main/libj/libjpeg-turbo/libjpeg62-turbo_1.5.2-2+b1_amd64.deb
This is single unmet dependency for pve-qemu on ubuntu.

> I don't have anything against pve-qemu-kvm alternative on Debians. But on Ubuntus, it's not that straightforward and doesn't look good to me to enable it in the packages.

Well, it's up to you. I know that my installation is not so common, bu in my opinion it is working quite stable and does not create any conflicts on my ubuntu system at least from the last year.

So I don't see the problem to add pve-qemu as alternative to qemu dependency for ubuntu packages too, but if you think that it is bad idea, I can correct my PR then.

**Comment by vholer** [comment]
For now, I have added `pve-qemu-kvm` alternative just for Debian package where this works flawlessly.

I still have the same objections against Ubuntu, but I'll leave the issue opened for now....

Thanks.
